### ISSUE TITLE
[Assignment 0] An example assignment

### ISSUE THREAD

**Issue by gvegayon** [USCbiostats/PM566#17]
# Discussion for Week [#] assignment

1. The file for this week's assignment can be downloaded from [here](#). The specific
   instructions for the assignment will be included in the zipfile (follow the instructions
   [here](github.com/USCbiostats/PM566/raw/master/assignments-instructions.md)).

2. Once you are done with the assignment, we encourage you to either add the URL to this issue in
   your last commit message, or create a new issue in your repository including a link to this issue.

3. We will provide feedback directly to your repository.

This assignment is due by [#].

**Comment by meredithfranklin** [comment]
Hi George, the links are not working -- could you check them?

**Comment by gvegayon** [comment]
> Hi George, the links are not working -- could you check them?

This is just an example of an assignment that I will be using for week 2, it is not a real assignment :P. I will add a bit more of context  later.
