### ISSUE TITLE
Week 8 (Midterm)

### ISSUE THREAD

**Issue by gvegayon** [USCbiostats/PM566#27]
- This week there will be no class or lab.
- You will have the entire week to work on your project. The midterm instructions are [available here](https://elastic-khorana-70231e.netlify.app/assignment/08-midterm/). 
- As we have been doing throughout the term, once you are done with your report, reference this issue in your last commit using [Github's auto-links](https://docs.github.com/en/github/writing-on-github/autolinked-references-and-urls).
- The midterm is due on Friday, October 9th, 2020 by midnight Pacific time.

**Comment by jiqingwu1997** [comment]
https://github.com/jiqingwu1997/pm566midterm
