### ISSUE TITLE
New slide not rendering when it should

### ISSUE THREAD

**Issue by AbigailHorn** [USCbiostats/PM566#32]
@gvegayon this is the first place the issue happens ... you'll see if you compile it.

https://github.com/USCbiostats/PM566/blob/b1588a33e05566b636c4f499b0257df72db4e52f/static/slides/11-interactive-viz/slides.Rmd#L223 

and the second place it happens:

https://github.com/USCbiostats/PM566/blob/b1588a33e05566b636c4f499b0257df72db4e52f/static/slides/11-interactive-viz/slides.Rmd#L260

etc.

Issue crops up identically after text, code chunks, graphs, whatever. Can't find the pattern. Let me know if you figure it out!!

**Comment by AbigailHorn** [comment]
Ahh it's in config/default! I couldn't find it. Thanks @gvegayon !

**Comment by gvegayon** [comment]
I honestly did not know where it was. To look for it I used the `grep` command:

```bash
# Look for "Meredith" in any file at this level
grep Meredith *.*
# Look for "Meredith" in any file within this level
$ grep Meredith */*.*
# Look for "Meredith" in any file two levels down
$ grep Meredith */*/*.*
```

The last returned the following:

```bash
george@xps:PM566$ grep Meredith */*/*.*
config/_default/params.yaml:author: Meredith Franklin, George Vega Yon, Emil Hvitfeldt, Abigail Horn
config/_default/params.yaml:    Meredith Franklin,
public/assignment/index.html:                    Meredith Franklin, George Vega Yon, Emil Hvitfeldt, Abigail Horn</a>
public/authors/index.html:                    Meredith Franklin, George Vega Yon, Emil Hvitfeldt, Abigail Horn</a>
public/class/index.html:                    Meredith Franklin, George Vega Yon, Emil Hvitfeldt, Abigail Horn</a>
public/reading/index.html:                    Meredith Franklin, George Vega Yon, Emil Hvitfeldt, Abigail Horn</a>
public/reference/index.html:                    Meredith Franklin, George Vega Yon, Emil Hvitfeldt, Abigail Horn</a>
public/schedule/index.html:                    Meredith Franklin, George Vega Yon, Emil Hvitfeldt, Abigail Horn</a>
public/syllabus/index.html:                    Meredith Franklin, George Vega Yon, Emil Hvitfeldt, Abigail Horn</a>
```

**Comment by AbigailHorn** [comment]
Awesome, thanks for the pro tip! I used grep but didn't know about the */*
level commands. Always learn something when I ask you a question!
