### ISSUE TITLE
Adding my name to instructor list

### ISSUE THREAD

**Issue by AbigailHorn** [USCbiostats/PM566#35]
https://github.com/USCbiostats/PM566/blob/74c99c69b56b9bf9826dadd3e32f1d0a905d0b46/public/index.html#L604

Hey @gvegayon , I am trying to add my name to the instructor list and did so in the relevant HTML files including the one referenced here, and I force pushed the `public` folder when I pushed changes, but not seeing the change made in the visible files. Can you refer me to the `.Rmd` file is in the repository where I can add my name? Thanks!

**Comment by gvegayon** [comment]
Solved in https://github.com/USCbiostats/PM566/commit/e2a08c61a9e2e8e44694701c3ba92d8408e1f2ee The public folder is automatically created. You need to update the yml as I did in the aforementioned commit.
