### ISSUE TITLE
Week 14 (Final Project)

### ISSUE THREAD

**Issue by meredithfranklin** [USCbiostats/PM566#37]
# Final Project

1. The instructions for the final project are [here](https://elastic-khorana-70231e.netlify.app/assignment/14-final/). 

2. Please provide your final project website url and don't forget that the pdf must be downloadable from it.

3. We will provide feedback directly to your repository.

The final project is due Wednesday November 25th by midnight PT.

**Comment by MingzhiYe16** [comment]
https://mingzhiye16.github.io/Final_Project/

**Comment by Shan-shan-666** [comment]
https://shan-shan-666.github.io/

**Comment by Weijia-H** [comment]
Final Project Website: https://weijia-h.github.io/Final-Project/

**Comment by RuowenWang123** [comment]
This is my PM566 final project website: https://ruowenwang123.github.io/PM566-Final/

**Comment by stephtring** [comment]
PM566 Final Project. The website link: https://stephtring.github.io/PM566Final/

**Comment by cbegay89** [comment]
PM566 Final Project Website: https://cbegay89.github.io/Final_Project/

**Comment by shawnyeusc** [comment]
final done https://github.com/shawnyeusc/midterm2

**Comment by yina-liu** [comment]
PM566 final website: https://yina-liu.github.io/PM566-FINAL/

**Comment by cnliyongsheng** [comment]
my finalized website: https://lysethan.github.io/COVID-19-US

**Comment by suyeonry** [comment]
Final Website : https://suyeonry.github.io/pm566_final

**Comment by asuasu95** [comment]
My final website : https://asuasu95.github.io/pm566final/

**Comment by Icygrey** [comment]
Final website: https://icygrey.github.io/pm566_lab12_hw5/

**Comment by slee2424** [comment]
Final Website: https://slee2424.github.io/PM-566-my-final-project/index.html

**Comment by jiaheche** [comment]
Final Website: https://jiaheche.github.io/pm566-final-project/
