### ISSUE TITLE
Week 13

### ISSUE THREAD

**Issue by AbigailHorn** [USCbiostats/PM566#49]
# Discussion for Week 13 / Lecture 12

Welcome to week 13, @USCbiostats/pm566-fall2021! We will be using this issue tracker for this week's sessions.

RMarkdown file for Lecture 12's slides can be found [here](https://github.com/USCbiostats/PM566/blob/master/website/static/slides/12-interactive-viz2/slides.Rmd)

Please use this issue to submit [lab 12](https://abigailhorn.github.io/PM566-final-project/12-lab.html) and [Assignment 4](https://uscbiostats.github.io/PM566/assignment/11-hw4/).

Once you have completed your lab 12 website, please add a link to the Github repository where you keep the file using [Github's auto-links](https://docs.github.com/en/github/writing-on-github/autolinked-references-and-urls)

**Comment by songruwa** [comment]
https://github.com/songruwa/PM566-HW4.git

**Comment by songruwa** [comment]
https://github.com/songruwa/Lab-12
@AbigailHorn
