### ISSUE TITLE
Week 16 - Assignment 5 and Final Project

### ISSUE THREAD

**Issue by ksiegmund** [USCbiostats/PM566#51]
# Final Project

1. The instructions for Assignment 5 are [here](https://uscbiostats.github.io/PM566/assignment/13-hw5/) and for the final project are [here](https://uscbiostats.github.io/PM566/assignment/14-final/).

2. For submitting both Assignment 5 and the Final Project, please provide your final project website url in the `README.md` file and don't forget that the pdf must be downloadable from your website.

3. We will provide feedback directly to your repository.

Assignment 5 is due Friday December 3rd by midnight PT.

The final project is due Friday December 10th by midnight PT.

**Comment by songruwa** [comment]
https://github.com/songruwa/Final-Project-1
