### ISSUE TITLE
Syllabus?

### ISSUE THREAD

**Issue by pmarjora** [USCbiostats/PM566#7]
Can somebody please remind me where we can find the syllabus? :-)

**Comment by EmilHvitfeldt** [comment]
The syllabus is located in the `content/syllabus/` folder :)

**Comment by pmarjora** [comment]
Thanks, but it doesn't seem to have what I want. Where's the listing of what topics will be covered each week?

**Comment by EmilHvitfeldt** [comment]
Are you thinking of the schedule?
https://elastic-khorana-70231e.netlify.app/schedule/

**Comment by pmarjora** [comment]
I am. Can we put a signpost somewhere, so that we know where to find this? Is that the course website?

**Comment by pmarjora** [comment]
I just found it, at the top of the github page. I added a reminder of where to find it.
