### ISSUE TITLE
Final Project

### ISSUE THREAD

**Issue by kstreet13** [USCbiostats/PM566#75]
This issue is intended to track submissions of the Final Project for the Fall 2023 version of PM 566.

Link to this issue in your final commit message to let us know when you are done. All we need is a link to your website, as we should be able to download your report from there.

**Comment by catherinele2020** [comment]
https://github.com/catherinele2020/PM566-Final

**Comment by lydiawangli** [comment]
https://uscbiostats.github.io/PM566/assignment/14-final/
